config/routes.rb
Rails.application.routes.draw do
  get '/tweets/new', to: 'tweets#new'

  get '/twitter/callback', to: 'sessions#create'
  post '/tweets/create', to: 'tweets#create'
  get '/tweets/error', to: 'tweets#error'

  resources :authentications
  get 'home/index'
  get '/vote/quote_count/:quote_id', to: 'votes#quote_count'
  get '/favorite_quotes/user', to: 'favorite_quotes#user'
  get '/search', to: 'searches#search'
  get '/typeahead', to: 'searches#typeahead'
  get '/search_json', to: 'searches#search_json'

  get '/category_ajax', to: 'categories#category_ajax'
  get '/author_ajax', to: 'authors#author_ajax'

  put 'comments/:content/:quote_id/:user_id', to: 'comments#destroy_from_params', as: 'comment_destroy'
  put 'favorite_quotes/:quote_id/:user_id', to: 'favorite_quotes#destroy_from_params', as: 'favorite_quote_destroy'
  put 'votes/:quote_id/:user_id', to: 'votes#destroy_from_params', as: 'vote_destroy'
  put 'quotes/:content/:author/:user_id', to: 'quotes#destroy_from_params', as: 'quote_destroy'

  resources :favorite_quotes
  resources :votes
  resources :categories
  resources :quotes do
    put :favorite, on: :member    # favorite_quote_path(@quote)
    resources :comments
  end
  resources :authors
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  root 'home#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author
  # belongs_to :submitter, class_name: 'User', foreign_key: 'user_id' if keep tracking of user-submissions does not work
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :users, :through => :votes
  has_many :comments, dependent: :destroy
  has_many :categorizations, dependent: :destroy
  has_many :categories, :through => :categorizations
  has_many :favorite_quotes, dependent: :destroy
  has_many :favorited_by, through: :favorite_quotes, source: :user  # users that favorite a quote

  accepts_nested_attributes_for :author
  accepts_nested_attributes_for :categories

  validates :content, presence: true
  validates :content_hash, uniqueness: {scope: :author, case_sensitive: false,
                    message: "quote should be unique per author"}
  validates :author, presence: true
  validates :user, presence: true

  # This determines how many quotes to display per page
  paginates_per 7

  trigger.after(:insert) do
    "UPDATE authors SET quote_count = quote_count + 1 WHERE NEW.author_id = id;"
  end

  trigger.after(:update) do
    "UPDATE authors SET quote_count = quote_count + 1 WHERE NEW.author_id = id;"\
    "UPDATE authors SET quote_count = quote_count - 1 WHERE OLD.author_id = id;"
  end

  trigger.after(:delete) do
    "UPDATE authors SET quote_count = quote_count - 1 WHERE OLD.author_id = id;"
  end

  def self.search(search, current_user)
    @where = "categories.content LIKE '%#{search}%' OR authors.name LIKE '%#{search}%'"
    if !current_user.nil?
        @quotes = Quote.joins(:categories)
                       .joins(:author)
                       .joins("LEFT JOIN( select id as vote_id, quote_id, value as vote_value from votes 
                               WHERE user_id = " + current_user.id.to_s + ") as user_votes on quotes.id = user_votes.quote_id") 
                       .joins("LEFT JOIN( SELECT id as favorite_ID, quote_id from favorite_quotes 
                                          WHERE user_id = " + current_user.id.to_s + ") as favorites on quotes.id = favorites.quote_id")
                       .where(@where)
                       .order(vote_count: :desc)
                       .select("quotes.id, quotes.content, quotes.updated_at, authors.name as author_name, authors.id as author_id, favorite_id, vote_id, vote_value, vote_count")
                       .all
    else 
        @quotes = Quote.joins(:categories)
                       .joins(:author)
                       .where(@where)
                       .order(vote_count: :desc)
                       .select("quotes.id, quotes.content, quotes.updated_at, authors.name as author_name, authors.id as author_id, vote_count")
                       .all
    end

    return @quotes
  end

  def category_list=(categories_string)
    category_names = categories_string.split(",").collect{ |category|
      category.strip.downcase
    }.uniq
    @categories = category_names.collect{ |name| Category.find_or_create_by(content: name)}
    self.categories = @categories
  end

  def category_list
    self.categories.collect do |category|
      category.content
      end.join(", ")
  end

  def as_json(options={})
    super(:only => [:id, :content],
    :include => {
        :author => {:only => [:id, :name]},
        :categories => {:only => [:id, :content]}
    })
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  require 'digest/md5'

  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  # Deprecated
  def index
    @has_search = false

    if params[:search] && !params[:search].empty?
      @has_search = true

      @search_quotes = Quote.search(params[:search], current_user).page(params[:page])
    else
      @search_quotes = nil
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.includes(:author, :categories, {comments: :user}).find(params[:id])
    @comment = Comment.new
    @categories = @quote.categories.map {|c| '#' + c.content.gsub(/\s+/, "")}.join(' ')
    @tweet = "#{@quote.content} -#{@quote.author.name} #{@categories}".truncate(140)
    respond_to do |format|
        format.html { }
        format.json { render json: @quote.as_json() }
    end
  end


  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.includes(:author, :categories).find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    if params[:cancel].present?
      redirect_to root_url
      return
    end

    author_name = quote_params[:author_attributes][:name]
    @author = Author.where(name: author_name).first_or_create

    @quote = Quote.new(quote_params.except("author_attributes"))
    @quote.author = @author
    @quote.user_id = (current_user.nil?)? nil : current_user.id
    @quote.content_hash = Digest::MD5.hexdigest(quote_params[:content].downcase)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote.as_json(), status: :created }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def favorite

  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])
    if params[:cancel].present?
      redirect_to root_url
      return
    end

    author_name = quote_params[:author_attributes][:name]
    @author = Author.where(name: author_name).first_or_create
    @quote.attributes = quote_params.except("author_attributes")
    @quote.author = @author
    @quote.content_hash = Digest::MD5.hexdigest(quote_params[:content].downcase)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /quotes/:content/:author/:user_id
  # PUT /quotes/:content/:author/:user_id.json
  def destroy_from_params
    @author = Author.where(name: params[:author]).first
    @quote = Quote.where(content: params[:content], author_id: @author.id).first
    if !@quote.nil?
      @quote.destroy
    end
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Deprecated
    def set_quote
      # @quote = Quote.includes(:author, :user, :categories, {comments: :user}).find(params[:id])
      #Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:content, :user_id,  :category_list, :author_attributes => [:name])
    end

end

app/helpers/quotes_helper.rb
module QuotesHelper
  def cache_key_for_quotes(quotes, tab, page)
    max_updated_at = quotes.maximum(:updated_at).try(:utc).try(:to_s, :number)
    if page.nil?
      page = 1
    end
    "quotes/tab-#{tab}/page-#{page}/#{max_updated_at}"
  end

  def cache_key_for_quote(quote, display_author, render_search)
    updated_at = quote.updated_at.try(:utc).try(:to_s, :number)
    "quote/#{quote.id}/#{display_author.to_s}/#{render_search.to_s}/#{updated_at}"
  end

end

app/views/quotes/_form.html.erb
<%= form_for(setup_quote(@quote)) do |f| %>
    <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <div class="field" name="">
        <%= f.label :content %><br>
        <%= f.text_area :content, placeholder: "Enter quote text", class: "form-control", rows:"5"%>
      </div>
    </div>

    <%= f.fields_for :author do |ff| %>
        <div class="form-group">
          <div class="field">
            <%= ff.label :name, "Author"%><br>
            <%= ff.text_field :name, placeholder: "Enter author's name", class: "form-control" %>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <div class="field">
        <%= f.label :category_list, "Categories" %> <br>
        <%= f.text_field :category_list, placeholder: "Enter categories separated by comma", class: "form-control" %>
      </div>
    </div>

    <%= button_tag class: "btn btn-primary" do %>
      Submit
    <% end%>

    <%= f.submit 'Cancel', :name => 'cancel', class: "btn btn-default", style: "float: right"%>

<% end %>

app/views/quotes/_modal.html.erb
<div class="modal fade" id="myModal<%= quote.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Send a Tweet</h4>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
            <div class="row">
              <% if @allow_twitter %>
                  <%= render partial: 'tweets/form', locals: {tweet: tweet, quote: quote, id: "myModal#{quote.id}"} %>
              <% else %>
                  <p>You must log in to send a tweet.</p>
                  <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quotes/_quote.html.erb
<% @search_quotes.each do |quote| %>
  <div class="quote row">
      <div class="col-xs-2 vote">
        <a href="#"><span class="fa fa-2x fa-chevron-up" aria-hidden="true"></span></a>
        <h4 class="vote-count">1337</h4>
        <a href="#"><span class="fa fa-2x fa-chevron-down" aria-hidden="true"></span></a>
      </div>
      <div class="col-xs-8 quote-text panel panel-default center">
        <div class="panel-body"><%= quote.content %> - <%= quote.author_name %></div>
      </div>
      <div class="col-xs-2 center quote-buttons">
        <div class="btn-group ">
          <button type="button" class="btn btn-default">
            <span class="fa fa-lg fa-heart-o" aria-hidden="true"></span>
          </button>
          <button type="button" class="btn btn-default">
            <span class="fa fa-lg fa-comment" aria-hidden="true"></span>
          </button>
        </div>
      </div>
  </div>
<% end %>

app/views/quotes/_quote_block.html.erb
<%
    display_author = true if local_assigns[:display_author].nil?
    author = nil if local_assigns[:author].nil?
    categories = nil if local_assigns[:categories].nil?
%>
<% quotes.each do |quote| %>
      <%
         @author_string = author.nil? ? quote.author_name : author
         @categories_string = categories.nil? ? quote.categories.map {|c| '#' + c.content.gsub(/\s+/, "")}.join(' ') : "##{categories.content}"
         @tweet_content = "#{quote.content} -#{@author_string} #{@categories_string}".truncate(140)
      %>
    <%# cache_unless (params[:tab].nil? || params[:tab] == "trending"), cache_key_for_quote(quote, params[:tab], params[:page]) do %>
        <div class="quote row vertical-align">
            <div class="row-same-height">
            <div class="col-xs-2 col-xs-height col-middle vote vote-<%=quote.id%>">
                <% if user_signed_in? %>
                    <%= render partial: "votes/quote_vote", locals: {quote: quote, current_user_id: current_user.id} %>
                <% else %>
                    <span class="fa fa-2x fa-chevron-up gray" aria-hidden="true" data-toggle="tooltip" data-trigger="hover" title="Sign in to upvote"></span>
                    <h4 class="vote-count"><%= Vote.quote_count(quote.id) %> </h4>
                    <span class="fa fa-2x fa-chevron-down gray" aria-hidden="true" data-toggle="tooltip" data-trigger="hover" data-placement="bottom" title="Sign in to downvote"></span>
                <% end %>
            </div>
            <% cache cache_key_for_quote(quote, display_author), skip_digest: true do %>
                <div class="col-xs-8 col-xs-height quote-text panel panel-default center" id="quote-panel">
                    <% div_id = "quote_#{quote.id}" %>
                    <div onclick="location.href='<%=quote_path(quote.id)%>';" style="cursor: pointer;" class="panel-body quote-content no-highlight over">
                        <%= quote.content %>
                        <% if display_author %>
                            <div class="author-name">-  <a class="no-bubble" href="<%= author_path(quote.author_id) %>"><%= quote.author_name %></a> </div>
                        <% end %>
                        <br>
                      <%= javascript_tag do %>
                          $('.no-bubble').click(function(event) {
                            event.stopImmediatePropagation();
                          });

                      <% end %>
                    </div>
                </div>
            <% end %>
    <div class="col-xs-2 col-xs-height col-middle center quote-buttons">
        <div class="quote-buttons">
            <% if user_signed_in? %>
                <%
                   @favorite = FavoriteQuote.where(quote_id: quote.id, user_id: current_user.id).first
                %>
                <div class="favorite-<%=quote.id%>">
                    <%= render partial: "favorite_quotes/favorite_block", locals: {quote_id: quote.id, favorite: @favorite, current_user_id: current_user.id} %>
                </div>
            <% else %>
                 <button style="cursor: default;pointer-events: auto;" type="submit" class="btn btn-default disabled" data-toggle="tooltip" data-trigger="hover" title="Sign in to favorite">
                    <span class="fa fa-2x fa-heart-o" aria-hidden="true"></span>
                </button>
            <% end %>
                 <button href="#myModal<%= quote.id%>" role="button" class="btn btn-default" data-toggle="modal" data-target="#myModal<%= quote.id%>">
                    <span class="fa fa-2x fa-twitter" aria-hidden="true"></span>
                 </button>
                 <%= render partial: "quotes/modal", locals: {quote: quote, tweet:@tweet_content } %>
            </div>
            </div>
        </div>
    </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Edit a Quote</h1>

<hr>

<%= render 'form' %>

app/views/quotes/index.html.erb
<!--<%= javascript_include_tag "validate" %>-->
<% cache 'search', skip_digest: true do %>
<div class="row">
  <div class="page-header">
    <h1>Search Results </h1>
  </div>

  <%= form_tag(quotes_path, :method => "get", id: "search-form",
               :class => "form-inline", :name => "search-form", :onsubmit => "return (validate());") do %>
      <div class="input-group">
        <span class="input-group-addon searchbar" id="search-label">Search</span>

        <div class="form-group searchbar-text" name="search-bar">
          <%= text_field_tag :search, params[:search],
                             placeholder: "Search Quotes or Authors",
                             class: "form-control searchbar-text" %>
        </div>
        <span class="input-group-btn searchbar">
            <button type="submit" class="btn btn-default">
              <span class="fa fa-search" aria-hidden="true"></span>
            </button>
        </span>
      </div>
  <% end %>
</div>

<br>
<% end %> <!-- end cache -->
<div>
  <% if @search_quotes.present? %>
      <%= render partial: "quotes/quote_block", locals: {quotes: @search_quotes} %>
  <% elsif @has_search %>
      <p>There are no quotes containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

<% unless @search_quotes.nil? %>
    <div>
      <div class="pages">
        <div class="left-arrow"><%= link_to_previous_page @search_quotes, '<i class="fa fa-angle-double-left fa-3x"></i>'.html_safe, :params => {:search => params[:search]} %></div>
        <div class="page-number"><%= params[:page] %></div>
        <%= link_to_next_page @search_quotes, '<i class="fa fa-angle-double-right fa-3x"></i>'.html_safe, :params => {:search => params[:search]} %>
      </div>
    </div>
<% end %>

app/views/quotes/new.html.erb
<h1>Submit a Quote</h1>

<hr>

<%= render 'form' %>

app/views/quotes/show.html.erb
<%= cache [@quote, @quote.comments.size], skip_digest: true do %>
<p id="notice"><%= notice %></p>
<div id="alert-placeholder"></div>

    <h2 class="quote-content"><%= "\"#{@quote.content}\""%>&nbsp;&nbsp;&nbsp;
        <br>
        <i><small class="author-name">- <%= link_to @quote.author.name, author_path(@quote.author)%></small></i>
    </h2>
    <br>
    <hr class="no-padding">
    <p style="font-size: 10px; float: right">Submitted by: <%= @quote.user.email %></p>
    <br>
    <p>
      <strong>Categories:</strong>
        <% @quote.categories.each do |category| %>
            <%= link_to category.content.capitalize, category_path(category)%><%=',' unless category.equal? @quote.categories.last %>
        <% end %>
    </p>

    <hr>
    <% unless @quote.comments.size <= 5 %>
        <a id='see-more' onclick="showComments();">Show More Comments</a>
    <% end %>
    <% @quote.comments.each_with_index do |comment, index| %>
        <%
            @class = ""
            if index < @quote.comments.size - 5
                @class += "comment-hide"
            end
        %>
        <%= div_for(comment, class: @class) do %>
            <sup>
                <strong><%= comment.user.email %></strong>
                From <%= time_ago_in_words(comment.created_at)%> ago
            </sup>
            <div>
              <%= comment.content %>
            </div>
        <% end %>
    <% end %>
<% end %> <!-- end caching -->
    <% if !current_user.nil? %>
        <%= render 'comments/form', :object => @comment %>
    <% end %>
    <hr>

    <% if !current_user.nil? && !current_user.provider.nil? && current_user.provider.include?("twitter") %>
        <!--<p>Click The link below to send a tweet.</p>-->
        <!--<%= link_to "Send a Tweet", tweets_new_path(message: @tweet) %>-->
        <%= render partial: 'tweets/form', locals: {tweet: @tweet, quote: @quote, id: @quote.id} %>
    <% else %>
        <p>You must log in to send a tweet.</p>
        <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% end %>

    <br>
    <br>

    <%= link_to 'Edit', edit_quote_path(@quote) %> |
    <%= link_to 'Back', root_path %>