config/routes.rb
Rails.application.routes.draw do
  get '/tweets/new', to: 'tweets#new'

  get '/twitter/callback', to: 'sessions#create'
  post '/tweets/create', to: 'tweets#create'
  get '/tweets/error', to: 'tweets#error'

  resources :authentications
  get 'home/index'
  get '/vote/quote_count/:quote_id', to: 'votes#quote_count'
  get '/favorite_quotes/user', to: 'favorite_quotes#user'
  get '/search', to: 'searches#search'
  get '/typeahead', to: 'searches#typeahead'
  get '/search_json', to: 'searches#search_json'

  get '/category_ajax', to: 'categories#category_ajax'
  get '/author_ajax', to: 'authors#author_ajax'

  put 'comments/:content/:quote_id/:user_id', to: 'comments#destroy_from_params', as: 'comment_destroy'
  put 'favorite_quotes/:quote_id/:user_id', to: 'favorite_quotes#destroy_from_params', as: 'favorite_quote_destroy'
  put 'votes/:quote_id/:user_id', to: 'votes#destroy_from_params', as: 'vote_destroy'
  put 'quotes/:content/:author/:user_id', to: 'quotes#destroy_from_params', as: 'quote_destroy'

  resources :favorite_quotes
  resources :votes
  resources :categories
  resources :quotes do
    put :favorite, on: :member    # favorite_quote_path(@quote)
    resources :comments
  end
  resources :authors
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :quote #, touch: true
  belongs_to :user

  validates :content, presence: true
  validates :quote, presence: true
  validates :user, presence: {message: "user should be logged in to comment"}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :only => [:new, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /comments
  # GET /comments.json
  def index
    @quote = Quote.find(params[:quote_id])
    @comments = @quote.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @quote = Quote.find(params[:quote_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @quote = Quote.find(params[:quote_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @quote = Quote.find(params[:quote_id])
    @userid = (current_user.nil?) ? nil : current_user.id
    @comment = Comment.new(content: comment_params[:content], quote_id: @quote.id, user_id: @userid)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to quote_path(params[:quote_id]), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to quote_path(params[:quote_id]), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/:quote_id/comments/1
  # DELETE /quotes/:quote_id/comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to quote_path(params[:quote_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /comments/:content/:quote_id/:user_id
  # PUT /comments/:content/:quote_id/:user_id.json
  def destroy_from_params
    @comment = Comment.where(content: params[:content], quote_id: params[:quote_id], user_id: params[:user_id]).first
    if !@comment.nil?
      @comment.destroy
    end
    respond_to do |format|
      format.html { redirect_to quote_path(params[:quote_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@quote, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% if !current_user.nil? %>
      <div class="form-group">
        <div class="field">
          <%= f.label :content, "Commenting as: #{current_user.email}" %><br>
          <%= f.text_area :content, class:"form-control", rows:"4"%>
        </div>
      </div>
    <% end %>

    <%= button_tag class: "btn btn-primary" do %>
        Save
    <% end%>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', quote_comment_path(@quote, @comment) %> |
<%= link_to 'Back', quote_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Quote</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.quote.content %></td>
        <td><%= comment.user.email %></td>
        <td><%= link_to 'Show', quote_comment_path(comment.quote, comment) %></td>
        <td><%= link_to 'Edit', edit_quote_comment_path(comment.quote, comment) %></td>
        <td><%= link_to 'Destroy', quote_comment_path(comment.quote, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_quote_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', quote_path(@quote.id) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @comment.quote.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.email %>
</p>

<%= link_to 'Edit', edit_quote_comment_path(@comment.quote, @comment) %> |
<%= link_to 'Back', quote_comments_path %>