config/routes.rb
Rails.application.routes.draw do
  get '/tweets/new', to: 'tweets#new'

  get '/twitter/callback', to: 'sessions#create'
  post '/tweets/create', to: 'tweets#create'
  get '/tweets/error', to: 'tweets#error'

  resources :authentications
  get 'home/index'
  get '/vote/quote_count/:quote_id', to: 'votes#quote_count'
  get '/favorite_quotes/user', to: 'favorite_quotes#user'
  get '/search', to: 'searches#search'
  get '/typeahead', to: 'searches#typeahead'
  get '/search_json', to: 'searches#search_json'

  get '/category_ajax', to: 'categories#category_ajax'
  get '/author_ajax', to: 'authors#author_ajax'

  put 'comments/:content/:quote_id/:user_id', to: 'comments#destroy_from_params', as: 'comment_destroy'
  put 'favorite_quotes/:quote_id/:user_id', to: 'favorite_quotes#destroy_from_params', as: 'favorite_quote_destroy'
  put 'votes/:quote_id/:user_id', to: 'votes#destroy_from_params', as: 'vote_destroy'
  put 'quotes/:content/:author/:user_id', to: 'quotes#destroy_from_params', as: 'quote_destroy'

  resources :favorite_quotes
  resources :votes
  resources :categories
  resources :quotes do
    put :favorite, on: :member    # favorite_quote_path(@quote)
    resources :comments
  end
  resources :authors
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  root 'home#index'

end

app/models/favorite_quote.rb
class FavoriteQuote < ActiveRecord::Base
  belongs_to :quote
  belongs_to :user
end

app/controllers/favorite_quotes_controller.rb
class FavoriteQuotesController < ApplicationController
  before_action :set_favorite_quote, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:user]

  # GET /favorite_quotes
  # GET /favorite_quotes.json
  def index
    @favorite_quotes = FavoriteQuote.all
  end

  # GET /favorite_quotes/1
  # GET /favorite_quotes/1.json
  def show
  end

  # GET /favorite_quotes/new
  def new
    @favorite_quote = FavoriteQuote.new
    
  end

  # GET /favorite_quotes/1/edit
  def edit
  end

  # POST /favorite_quotes
  # POST /favorite_quotes.json
  def create
    @favorite_quote = FavoriteQuote.where(quote_id: favorite_quote_params[:quote_id], user_id: favorite_quote_params[:user_id]).first
    @present = @favorite_quote.present?
    if !@present
      @favorite_quote = FavoriteQuote.new(favorite_quote_params)
    end

    respond_to do |format|
      if !@present && @favorite_quote.save
        format.html { redirect_to @favorite_quote, notice: 'Favorite quote was successfully created.' }
        format.json { render json: @favorite_quote, status: :created }
        format.js {}
      else
        if @favorite_quote.destroy
          format.html { redirect_to favorite_quotes_url, notice: 'Favorite quote was successfully destroyed.' }
          format.json { head :no_content }
          format.js {}
        else
          format.html { render :new }
          format.json { render json: @favorite_quote.errors, status: :unprocessable_entity }
          format.js {}
        end
      end
    end
  end

  # PATCH/PUT /favorite_quotes/1
  # PATCH/PUT /favorite_quotes/1.json
  def update
    respond_to do |format|
      if @favorite_quote.update(favorite_quote_params)
        format.html { redirect_to @favorite_quote, notice: 'Favorite quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_quote }
      else
        format.html { render :edit }
        format.json { render json: @favorite_quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_quotes/1
  # DELETE /favorite_quotes/1.json
  def destroy
    respond_to do |format|
      if @favorite_quote.destroy
        format.html { redirect_to favorite_quotes_url, notice: 'Favorite quote was successfully destroyed.' }
        format.json { head :no_content }
        format.js {}
      else
        format.json { head :no_content }
      end
    end
  end

  # PUT /favorite_quotes/:quote_id/:user_id
  # PUT /favorite_quotes/:quote_id/:user_id.json
  def destroy_from_params
    @favorite = FavoriteQuote.where(quote_id: params[:quote_id], user_id: params[:user_id]).first
    if !@favorite.nil?
      @favorite.destroy
    end
    respond_to do |format|
      format.html { redirect_to favorite_quotes_url, notice: 'Favorite quote  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /favorite_quotes/user
  def user
    @user_favorites = 
        Quote.joins(
           "INNER JOIN(  select quote_id 
            from favorite_quotes 
            where user_id = #{current_user.id}) 
            as favorites on quotes.id = favorites.quote_id")
                .joins(:author)
                .select("quotes.id, quotes.content, quotes.updated_at, quotes.vote_count, authors.name as author_name, authors.id as author_id")
                .all

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_quote
      @favorite_quote = FavoriteQuote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_quote_params
      params.require(:favorite_quote).permit(:quote_id, :user_id)
    end
end

app/helpers/favorite_quotes_helper.rb
module FavoriteQuotesHelper
end

app/views/favorite_quotes/_favorite_block.html.erb
<!-- Needs quote_id, favorite_id and current_user -->
<% @favorite_quote = FavoriteQuote.new %>

<% if favorite_id.nil? %>
    <%= form_for(@favorite_quote, :html => {:class => "btn-group", :remote => true}) do |f| %>
        <%= f.hidden_field :quote_id, value: quote_id %>
        <%= f.hidden_field :user_id, value: current_user_id %>
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
            <span class="fa fa-2x fa-heart-o" aria-hidden="true"></span>  
        <% end %>
    <% end %>

    
<% else %>
    <%= form_tag({controller: "favorite_quotes", action: "destroy", id: favorite_id}, method: "delete", class: "btn-group", remote: true) do |f| %>
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
            <span class="fa fa-2x fa-heart" aria-hidden="true"></span>
        <% end %>
    <% end %>

<% end %>

app/views/favorite_quotes/_form.html.erb
<%= form_for(@favorite_quote) do |f| %>
  <% if @favorite_quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite_quote.errors.count, "error") %> prohibited this favorite_quote from being saved:</h2>

      <ul>
      <% @favorite_quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_id %><br>
    <%= f.text_field :quote_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorite_quotes/create.js.erb
//alert("created!");
$('.favorite-<%=@favorite_quote.quote_id%>').html(
    "<%= j render(
        :partial => "favorite_quotes/favorite_block",
        :locals => {
            :favorite_id => @favorite_quote.id,
            :quote_id => @favorite_quote.quote_id, 
            :current_user_id => @favorite_quote.user_id
        }
    ) %>");

app/views/favorite_quotes/destroy.js.erb
//alert("destroyed!");
$('.favorite-<%=@favorite_quote.quote_id%>').html(
    "<%= j render(
        :partial => "favorite_quotes/favorite_block",
        :locals => {
            :favorite_id => nil,
            :quote_id => @favorite_quote.quote_id, 
            :current_user_id => @favorite_quote.user_id
        }
    ) %>");

app/views/favorite_quotes/edit.html.erb
<h1>Editing Favorite Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite_quote %> |
<%= link_to 'Back', favorite_quotes_path %>

app/views/favorite_quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Favorite Quotes</h1>

<table>
  <thead>
      <tr>
          <th>Id </th>
      <th>Quote</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_quotes.each do |favorite_quote| %>
        <tr>
            <td><%= favorite_quote.id %> </td>
        <td><%= favorite_quote.quote_id %></td>
        <td><%= favorite_quote.user_id %></td>
        <td><%= link_to 'Show', favorite_quote %></td>
        <td><%= link_to 'Edit', edit_favorite_quote_path(favorite_quote) %></td>
        <td><%= link_to 'Destroy', favorite_quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite quote', new_favorite_quote_path %>

app/views/favorite_quotes/new.html.erb
<h1>New Favorite Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', favorite_quotes_path %>

app/views/favorite_quotes/show.html.erb
<p id="notice"><%= notice %></p>
<div id="alert-placeholder"></div>

<p>
  <strong>Quote:</strong>
  <%= @favorite_quote.quote_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @favorite_quote.user_id %>
</p>

<%= link_to 'Edit', edit_favorite_quote_path(@favorite_quote) %> |
<%= link_to 'Back', favorite_quotes_path %>

app/views/favorite_quotes/user.html.erb
<p id="notice"><%= notice %></p>
<div id="alert-placeholder"></div>

<div class="page-header">
  <h1> What are your favorite quotes? </h1>
</div>
<div class="row" id = "quotes">
    <% unless @user_favorites.nil? || @user_favorites.empty? %>
        <%= render partial: "quotes/quote_block", locals: {quotes: @user_favorites} %>
    <% else %>
            <p id="notice"> Looks like you haven't added any quotes to favorites yet! </p>
    <% end %>
</div>