config/routes.rb
Rails.application.routes.draw do
  get '/tweets/new', to: 'tweets#new'

  get '/twitter/callback', to: 'sessions#create'
  post '/tweets/create', to: 'tweets#create'
  get '/tweets/error', to: 'tweets#error'

  resources :authentications
  get 'home/index'
  get '/vote/quote_count/:quote_id', to: 'votes#quote_count'
  get '/favorite_quotes/user', to: 'favorite_quotes#user'
  get '/search', to: 'searches#search'
  get '/typeahead', to: 'searches#typeahead'
  get '/search_json', to: 'searches#search_json'

  get '/category_ajax', to: 'categories#category_ajax'
  get '/author_ajax', to: 'authors#author_ajax'

  put 'comments/:content/:quote_id/:user_id', to: 'comments#destroy_from_params', as: 'comment_destroy'
  put 'favorite_quotes/:quote_id/:user_id', to: 'favorite_quotes#destroy_from_params', as: 'favorite_quote_destroy'
  put 'votes/:quote_id/:user_id', to: 'votes#destroy_from_params', as: 'vote_destroy'
  put 'quotes/:content/:author/:user_id', to: 'quotes#destroy_from_params', as: 'quote_destroy'

  resources :favorite_quotes
  resources :votes
  resources :categories
  resources :quotes do
    put :favorite, on: :member    # favorite_quote_path(@quote)
    resources :comments
  end
  resources :authors
  devise_for :users, controllers: {:omniauth_callbacks => "omniauth_callbacks"}

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% cache 'layout', skip_digest: true do %>
<head>
  <title>Quotopia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav id="topbar" class="navbar navbar-default container-fluid">
        <div class="navbar-header" >
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="color:white;">Quotopia</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav" style="display:inline;">
<% end %>
                <% if user_signed_in? %>
                    <li class="<%=is_active('favorite_quotes')%>"><%= link_to "Favorites", '/favorite_quotes/user',
                        :class => "nav-link ", :id => "fave-nav", :method => :get %></li>
                <% end %>

                <li class="<%=is_active('authors')%>"><%= link_to "Authors", authors_path,
                    :class => "nav-link", :id =>"author-nav", :method => :get %></li>
                 <li class="<%=is_active('categories')%>"><%= link_to "Categories", categories_path, :class => "nav-link", :id =>"category-nav", :method => :get %></li>
           </ul>
            <ul class="nav navbar-nav navbar-right">
                <% unless user_signed_in? %>
                   <li class="<%=is_active('devise/sessions')%>"> <%= link_to "Sign in", new_user_session_path,
                        :class => " nav-link", :method => :get %></li>
                   <li> <%= link_to "Sign up", new_user_registration_path, :id => "sign-up-btn",
                        :class => "btn btn-default navbar-btn", :method => :get %></li>
                <% else %>
                   <li class="<%=is_active('devise/registrations')%>"> <%= link_to "My Account", edit_user_registration_path,
                        :class => " nav-link", :method => :get %></li>
                   <li>  <%= link_to "Logout", destroy_user_session_path,
                        :class => " nav-link", :method => :delete %></li>
                   <li class="navbar-text" style="color:white;"> <b><%= current_user.email %></b></li>
                <% end %>
            </ul>
        </div>
    </nav>
    <div id="main-container" class="container">
        <%= yield %>
    </div>

</body>
</html>